// Separate Mermaid bundle for QuickLook — only loaded when mermaid blocks exist
// This keeps the main renderer lean (~500KB) and defers the heavy Mermaid lib (~3.5MB)

import mermaid from "mermaid";

// Security note: SVG is generated by the Mermaid library from local markdown file
// content on the user's filesystem, not from untrusted external sources.
// This is the same pattern used in the main YAMV app (src/renderer.js).
window.renderMermaid = async function(container) {
  const blocks = container.querySelectorAll("code.language-mermaid");
  if (blocks.length === 0) return;

  const isDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
  mermaid.initialize({
    startOnLoad: false,
    theme: "base",
    themeVariables: isDark
      ? {
          background: "#1c1e20",
          primaryColor: "#292c2e",
          primaryTextColor: "#d8d8d8",
          primaryBorderColor: "#4c4c4c",
          secondaryColor: "#3a3d40",
          secondaryTextColor: "#d8d8d8",
          secondaryBorderColor: "#4c4c4c",
          tertiaryColor: "#3a3d40",
          tertiaryTextColor: "#d8d8d8",
          tertiaryBorderColor: "#4c4c4c",
          lineColor: "#74bef7",
          textColor: "#d8d8d8",
          mainBkg: "#292c2e",
          nodeBorder: "#74bef7",
          clusterBkg: "#1c1e20",
          clusterBorder: "#4c4c4c",
          titleColor: "#c6d5e0",
          edgeLabelBackground: "#292c2e",
          nodeTextColor: "#d8d8d8",
        }
      : {
          background: "#fafafa",
          primaryColor: "#f0f0f0",
          primaryTextColor: "#2c2c2c",
          primaryBorderColor: "#d7d7d7",
          secondaryColor: "#e5e5e5",
          secondaryTextColor: "#2c2c2c",
          secondaryBorderColor: "#d7d7d7",
          tertiaryColor: "#e5e5e5",
          tertiaryTextColor: "#2c2c2c",
          tertiaryBorderColor: "#d7d7d7",
          lineColor: "#cb4d49",
          textColor: "#2c2c2c",
          mainBkg: "#f0f0f0",
          nodeBorder: "#cb4d49",
          clusterBkg: "#fafafa",
          clusterBorder: "#d7d7d7",
          titleColor: "#2c2c2c",
          edgeLabelBackground: "#f0f0f0",
          nodeTextColor: "#2c2c2c",
        },
  });

  for (let i = 0; i < blocks.length; i++) {
    const block = blocks[i];
    const pre = block.parentElement;
    try {
      const { svg } = await mermaid.render("mermaid-ql-" + i, block.textContent);
      const div = document.createElement("div");
      div.className = "mermaid-diagram";
      // Safe: SVG output from Mermaid library processing local file content only
      div.innerHTML = svg;
      pre.replaceWith(div);
    } catch (e) {
      pre.classList.add("mermaid-error");
    }
  }
};
