// Standalone markdown renderer for QuickLook extension
// This gets bundled into a single IIFE that exposes window.renderMarkdown() and window.renderMermaid()

import markdownit from "markdown-it";
import footnote from "markdown-it-footnote";
import { full as emoji } from "markdown-it-emoji";
import abbr from "markdown-it-abbr";
import deflist from "markdown-it-deflist";
import taskLists from "markdown-it-task-lists";
import mark from "markdown-it-mark";
import hljs from "highlight.js";
import katex from "katex";
import mermaid from "mermaid";

const md = markdownit({
  html: true,
  linkify: true,
  typographer: true,
  highlight(str, lang) {
    if (lang === "mermaid") {
      return `<pre><code class="language-mermaid">${md.utils.escapeHtml(str)}</code></pre>`;
    }
    if (lang && hljs.getLanguage(lang)) {
      try {
        return `<pre class="hljs"><code>${hljs.highlight(str, { language: lang }).value}</code></pre>`;
      } catch (_) { /* fallback */ }
    }
    return `<pre class="hljs"><code>${md.utils.escapeHtml(str)}</code></pre>`;
  },
});

md.use(footnote);
md.use(emoji);
md.use(abbr);
md.use(deflist);
md.use(taskLists, { enabled: false });
md.use(mark);

// KaTeX inline math: $...$
function mathInline(state, silent) {
  if (state.src[state.pos] !== "$") return false;
  if (state.src[state.pos + 1] === "$") return false;
  const start = state.pos + 1;
  let end = start;
  while (end < state.posMax && state.src[end] !== "$") {
    if (state.src[end] === "\\") end++;
    end++;
  }
  if (end >= state.posMax) return false;
  if (!silent) {
    const token = state.push("math_inline", "math", 0);
    token.markup = "$";
    token.content = state.src.slice(start, end);
  }
  state.pos = end + 1;
  return true;
}

// KaTeX block math: $$...$$
function mathBlock(state, startLine, endLine, silent) {
  const startPos = state.bMarks[startLine] + state.tShift[startLine];
  if (startPos + 2 > state.eMarks[startLine]) return false;
  if (state.src.slice(startPos, startPos + 2) !== "$$") return false;
  if (silent) return true;
  let nextLine = startLine;
  let found = false;
  while (++nextLine < endLine) {
    const lineStart = state.bMarks[nextLine] + state.tShift[nextLine];
    const lineEnd = state.eMarks[nextLine];
    if (state.src.slice(lineStart, lineEnd).trim() === "$$") { found = true; break; }
  }
  if (!found) return false;
  const token = state.push("math_block", "math", 0);
  token.block = true;
  token.content = state.getLines(startLine + 1, nextLine, state.tShift[startLine], true);
  token.map = [startLine, nextLine + 1];
  token.markup = "$$";
  state.line = nextLine + 1;
  return true;
}

md.inline.ruler.after("escape", "math_inline", mathInline);
md.block.ruler.after("blockquote", "math_block", mathBlock, {
  alt: ["paragraph", "reference", "blockquote", "list"],
});

md.renderer.rules.math_inline = (tokens, idx) => {
  try {
    return katex.renderToString(tokens[idx].content, { throwOnError: false });
  } catch (e) {
    return `<span class="katex-error">${md.utils.escapeHtml(tokens[idx].content)}</span>`;
  }
};

md.renderer.rules.math_block = (tokens, idx) => {
  try {
    return `<div class="katex-block">${katex.renderToString(tokens[idx].content, {
      throwOnError: false,
      displayMode: true,
    })}</div>`;
  } catch (e) {
    return `<div class="katex-error">${md.utils.escapeHtml(tokens[idx].content)}</div>`;
  }
};

window.renderMarkdown = function(markdown) {
  return md.render(markdown);
};

// Mermaid post-render: converts code.language-mermaid blocks into SVG diagrams.
// Safe: SVG is generated by the Mermaid library from local markdown file content,
// not from untrusted external sources. Same pattern used in the main app (src/renderer.js:288).
window.renderMermaid = async function(container) {
  const blocks = container.querySelectorAll("code.language-mermaid");
  if (blocks.length === 0) return;

  const isDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
  mermaid.initialize({
    startOnLoad: false,
    theme: "base",
    themeVariables: isDark
      ? {
          background: "#1c1e20",
          primaryColor: "#292c2e",
          primaryTextColor: "#d8d8d8",
          primaryBorderColor: "#4c4c4c",
          secondaryColor: "#3a3d40",
          secondaryTextColor: "#d8d8d8",
          secondaryBorderColor: "#4c4c4c",
          tertiaryColor: "#3a3d40",
          tertiaryTextColor: "#d8d8d8",
          tertiaryBorderColor: "#4c4c4c",
          lineColor: "#74bef7",
          textColor: "#d8d8d8",
          mainBkg: "#292c2e",
          nodeBorder: "#74bef7",
          clusterBkg: "#1c1e20",
          clusterBorder: "#4c4c4c",
          titleColor: "#c6d5e0",
          edgeLabelBackground: "#292c2e",
          nodeTextColor: "#d8d8d8",
        }
      : {
          background: "#fafafa",
          primaryColor: "#f0f0f0",
          primaryTextColor: "#2c2c2c",
          primaryBorderColor: "#d7d7d7",
          secondaryColor: "#e5e5e5",
          secondaryTextColor: "#2c2c2c",
          secondaryBorderColor: "#d7d7d7",
          tertiaryColor: "#e5e5e5",
          tertiaryTextColor: "#2c2c2c",
          tertiaryBorderColor: "#d7d7d7",
          lineColor: "#cb4d49",
          textColor: "#2c2c2c",
          mainBkg: "#f0f0f0",
          nodeBorder: "#cb4d49",
          clusterBkg: "#fafafa",
          clusterBorder: "#d7d7d7",
          titleColor: "#2c2c2c",
          edgeLabelBackground: "#f0f0f0",
          nodeTextColor: "#2c2c2c",
        },
  });

  for (let i = 0; i < blocks.length; i++) {
    const block = blocks[i];
    const pre = block.parentElement;
    try {
      const { svg } = await mermaid.render("mermaid-ql-" + i, block.textContent);
      const div = document.createElement("div");
      div.className = "mermaid-diagram";
      div.innerHTML = svg; // Safe: Mermaid-generated SVG from local file content
      pre.replaceWith(div);
    } catch (e) {
      pre.classList.add("mermaid-error");
    }
  }
};
