import markdownit from "markdown-it";
import footnote from "markdown-it-footnote";
import { full as emoji } from "markdown-it-emoji";
import abbr from "markdown-it-abbr";
import deflist from "markdown-it-deflist";
import anchor from "markdown-it-anchor";
import tocDoneRight from "markdown-it-toc-done-right";
import frontMatter from "markdown-it-front-matter";
import hljs from "highlight.js";
import katex from "katex";

let frontMatterContent = null;

const md = markdownit({
  html: true,
  linkify: true,
  typographer: true,
  highlight(str, lang) {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return `<pre class="hljs"><code>${hljs.highlight(str, { language: lang }).value}</code></pre>`;
      } catch (_) {
        /* fallback below */
      }
    }
    return `<pre class="hljs"><code>${md.utils.escapeHtml(str)}</code></pre>`;
  },
});

md.use(footnote);
md.use(emoji);
md.use(abbr);
md.use(deflist);
md.use(anchor, { permalink: anchor.permalink.headerLink() });
md.use(tocDoneRight);
md.use(frontMatter, (fm) => {
  frontMatterContent = fm;
});

// KaTeX inline math: $...$
function mathInline(state, silent) {
  if (state.src[state.pos] !== "$") return false;
  if (state.src[state.pos + 1] === "$") return false;

  const start = state.pos + 1;
  let end = start;
  while (end < state.posMax && state.src[end] !== "$") {
    if (state.src[end] === "\\") end++;
    end++;
  }
  if (end >= state.posMax) return false;
  if (!silent) {
    const token = state.push("math_inline", "math", 0);
    token.markup = "$";
    token.content = state.src.slice(start, end);
  }
  state.pos = end + 1;
  return true;
}

// KaTeX block math: $$...$$
function mathBlock(state, startLine, endLine, silent) {
  const startPos = state.bMarks[startLine] + state.tShift[startLine];
  if (startPos + 2 > state.eMarks[startLine]) return false;
  if (state.src.slice(startPos, startPos + 2) !== "$$") return false;
  if (silent) return true;

  let nextLine = startLine;
  let found = false;
  while (++nextLine < endLine) {
    const lineStart = state.bMarks[nextLine] + state.tShift[nextLine];
    const lineEnd = state.eMarks[nextLine];
    if (state.src.slice(lineStart, lineEnd).trim() === "$$") {
      found = true;
      break;
    }
  }
  if (!found) return false;

  const token = state.push("math_block", "math", 0);
  token.block = true;
  token.content = state.getLines(startLine + 1, nextLine, state.tShift[startLine], true);
  token.map = [startLine, nextLine + 1];
  token.markup = "$$";
  state.line = nextLine + 1;
  return true;
}

md.inline.ruler.after("escape", "math_inline", mathInline);
md.block.ruler.after("blockquote", "math_block", mathBlock, {
  alt: ["paragraph", "reference", "blockquote", "list"],
});

md.renderer.rules.math_inline = (tokens, idx) => {
  try {
    return katex.renderToString(tokens[idx].content, { throwOnError: false });
  } catch (e) {
    return `<span class="katex-error">${md.utils.escapeHtml(tokens[idx].content)}</span>`;
  }
};

md.renderer.rules.math_block = (tokens, idx) => {
  try {
    return `<div class="katex-block">${katex.renderToString(tokens[idx].content, {
      throwOnError: false,
      displayMode: true,
    })}</div>`;
  } catch (e) {
    return `<div class="katex-error">${md.utils.escapeHtml(tokens[idx].content)}</div>`;
  }
};

const postRenderHooks = [];

export function addPostRenderHook(fn) {
  postRenderHooks.push(fn);
}

function renderFrontMatter(fm) {
  if (!fm) return "";
  return `<details class="front-matter"><summary>Front Matter</summary><pre><code class="language-yaml">${md.utils.escapeHtml(fm)}</code></pre></details>`;
}

export function render(markdown) {
  frontMatterContent = null;
  const html = md.render(markdown);
  const fmHtml = renderFrontMatter(frontMatterContent);
  return fmHtml + html;
}

export async function postRender(container) {
  const mermaidBlocks = container.querySelectorAll("code.language-mermaid");
  if (mermaidBlocks.length > 0) {
    const mermaid = (await import("mermaid")).default;
    mermaid.initialize({
      startOnLoad: false,
      theme: window.matchMedia("(prefers-color-scheme: dark)").matches
        ? "dark"
        : "default",
    });
    for (let i = 0; i < mermaidBlocks.length; i++) {
      const block = mermaidBlocks[i];
      const pre = block.parentElement;
      const graphDef = block.textContent;
      try {
        const { svg } = await mermaid.render(`mermaid-${i}`, graphDef);
        const div = document.createElement("div");
        div.className = "mermaid-diagram";
        // Safe: SVG generated by Mermaid library from local file content
        div.innerHTML = svg;
        pre.replaceWith(div);
      } catch (e) {
        pre.classList.add("mermaid-error");
      }
    }
  }

  for (const hook of postRenderHooks) {
    await hook(container);
  }
}
